a = input('Digite algo: ')
print('O tipo primitivo desse valor é ',type(a))
print('Só tem espaços ? :', a.isspace())
print('É um numero?     :', a.isnumeric())
print('È alfabético?    :', a.isalpha())
print('È alfanumerico?  :', a.isalnum())
print('È maiusculo?     :', a.isupper())
print('È minusculo?     :', a.islower())
print('È capitalizada?  :', a.istitle())
