 url: "http://exemplo.com"
 database: 
  host: "192.168.99.100"
  dbname: "ninjaflix"
  user: "postgres"
  password: "qaninja"
users:
    cat_manager:
      email: "peper_pots@stark.com"
      pass: "pwd123"